### ISSUE TITLE
Introduction to Reinforcement Learning (Sutton & Barto)

### ISSUE THREAD

**Issue by elliothuang** [ahmedbahaaeldin/From-0-to-Research-Scientist-resources-guide#1]
Hello friend, first of all thanks for putting this together.

Just wanted to let you know that the full 2nd edition of Intro to RL (Sutton & Barto) can be found here:

http://incompleteideas.net/book/the-book.html
http://incompleteideas.net/book/RLbook2020.pdf

**Comment by ahmedbahaaeldin** [comment]
@elliothuang THanks alot for the information. I will update it now
