### ISSUE TITLE
Linear Algebra link is not working.

### ISSUE THREAD

**Issue by zalimitless** [ahmedbahaaeldin/From-0-to-Research-Scientist-resources-guide#11]
On the front-page, the link for "Linear Algebra 4th Edition by Friedberg" seems to not be working.

Link: https://npqke7p41z.pdcdn2.xyz/dl2.php?id=187502855&h=fe4fe4abfa10c9c6a51456cdff771ba1&u=cache&ext=pdf&n=Linear%20algebra%204th%20edition

**Comment by BiswayanPaul** [comment]
I would like to solve this issue.
